### ISSUE TITLE
Error running morpho example

### ISSUE THREAD

**Issue by elisenovitski** [morphoorg/morpho#121]
**Describe the bug**
Today on my Mac, I pulled the master branch of morpho, started the docker container, sourced setup.sh, tried to run morpho_linear.yaml, and got the following error:

Traceback (most recent call last):
  File "/build/bin/morpho", line 64, in <module>
    myToolBox.Run()
  File "/build/lib/python3.6/site-packages/morpho/utilities/toolbox.py", line 151, in Run
    logger.debug("Configuration:\n{}".format(json.dumps(self.config_dict, indent=4)))
NameError: name 'json' is not defined

**Comment by guiguem** [comment]
@elisenovitski Thanks for reporting this bug.
However when looking into the source code of the master branch, the json.dumps does not happen at line 151 but later (https://github.com/morphoorg/morpho/blob/master/morpho/utilities/toolbox.py#L184).
Could you make sure you have the latest master and check the line 151 is making `json.dumps(...)`?

**Comment by elisenovitski** [comment]
@guiguem I did indeed pull the master of morpho before doing any of this. Here is the status now:
Elises-MacBook-Pro:morpho elisenovitski$ git branch
* master
Elises-MacBook-Pro:morpho elisenovitski$ git fetch
Elises-MacBook-Pro:morpho elisenovitski$ git status
On branch master
Your branch is up to date with 'origin/master'.

I see what you mean, that the master does not have the json.dumps on line 151. The local file that my error message refers to still does have the json.dumps on line 151, however. Do I need to rebuild morpho after having pulled it? If so, are there instructions for that somewhere? I think there used to be... I'm a little confused about which parts of morpho are built in the environment of the host machine and which are inside the Docker container.

**Comment by guiguem** [comment]
Solved
