### ISSUE TITLE
Divergence Plotting

### ISSUE THREAD

**Issue by taliaweiss** [morphoorg/morpho#126]
After Stan runs, display a grid of divergence plots for all parameters – like the 2-D histogram grid, but with points color coded depending on whether the saved divergence value is "0" or "1." Code for an individual plot in such a grid can be found at morpho/morpho/plot/histo.py in morpho1.

I believe that Mathieu and I agreed this figure should be displayed automatically when Stan is run (and is just there to give a sense of the divergence situation, so it would not have to be fancy).

**Comment by guiguem** [comment]
Done with #130
