### ISSUE TITLE
More diagnostic tools

### ISSUE THREAD

**Issue by guiguem** [morphoorg/morpho#61]
* [x] Automatically? generate trace plots
* [ ] Bayes plot (R) or do them ourselves [[here|https://github.com/stan-dev/bayesplot]] and [[here|http://mc-stan.org/bayesplot/articles/visual-mcmc-diagnostics.html]]
* [x] Quick diagnostics print/checks

**Comment by guiguem** [comment]
Third bullet: go and see https://github.com/project8/morpho/issues/57

**Comment by taliaweiss** [comment]
Replaced with more current issues (#125 and #126 ).
