### ISSUE TITLE
Documentation To-Do Items

### ISSUE THREAD

**Issue by taliaweiss** [morphoorg/morpho#69]
At the end of the Docathon, Joe J. and I discussed some documentation to-do items:

  1. Create a "Soon to Come" page in the docstrings that generally describes morpho2.

  2. Create a docstrings page on "Development" that explains what we imagine "developers" other than us would be doing (creating new processors), why they should use Docker, and what using Docker entails.
A related point: Joe and I discussed whether we should remove the Project 8 or neutrino physics specific plotting processors, and we thought it would be worth retaining at least one (perhaps "neutrino_params.py"), as an example of how other users could create processors specific to their own analyses. We could show/describe that example in the docstrings page on "Development."

  3. Provide a more detailed explanation of the purpose/usage pf resampling.py (@guiguem – might you be able to help with this?).

I'll return to these items later this week, and others should feel free to work on them, as well.

**Comment by taliaweiss** [comment]
I see that a "Contribute" docs page (a more aptly named version of the "Development" page I suggested) already exists – apologies for missing that. My recommendations for additions to the page still apply.

**Comment by taliaweiss** [comment]
1. Sorry, a sphinx page on RTD is good – I got the terms confused. I agree, about the GitHub issue tracker.
3. Perfect – thanks so much. I'll update the relevant README to reflect that information.

**Comment by guiguem** [comment]
Documentation on RTD appears to be broken: repair it!
